### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by roger-** [dkasak/pacal#1]
Noticed that this doesn't support Python 3 out of the box. The 2to3 tool seems to get it to install, but I get an error with the following:

``` python
Y = UniformDistr(1,2)
X = UniformDistr(3,4)
A = atan(Y / X)

>> TypeError: unsupported operand type(s) for /: 'UniformDistr' and 'UniformDistr'
```

**Comment by dkasak** [comment]
@roger-, check out the [python3 branch in jszymon's new repository](https://github.com/jszymon/pacal/tree/python3). There has been some activity recently that adapts pacal to Python 3, but I'm not sure in what state it is.
